### PR TITLE
Condensed added to master (PR includes notes)

### PR DESCRIPTION
**Pull request by laerm0**
I have added the condensed weights to the master Glyphs file.

- bold and light came from TTF source
- regular, semibold, and extrabold were interpolated

This is not ready to go yet. Some things still need work.

- [ ] The interpolated condensed Hebrew is something I don't feel qualified to judge. I asked @meirsadan if he would check these glyphs and he agreed. Meir, a note on the extrabold in particular: the glyphs that have the dagesh nestled in between strokes were often smushed together. The extrabold regular width had a smaller dagesh variation for those glyphs and I have essentially done the same for the condensed. 
- [ ] I am not in love with the old-style figures in the extrabold condensed, but I will take a break from tweaking them for now.
- [ ] I would like to improve the fractions, both the OT code and the glyphs themselves. I am going to turn them into composites first of all and research better ways to do the OT than what Glyphs automagically creates.

Finally, I didn't know what the best way was to track what @meirsadan does. Meir, do you want to just fix anything that needs fixing in the Hebrew or do you want to pass notes to me? Also, I dunno the mechanics of github in this way: should @davelab6 accept this PR as an intermediate thing and then Meir can fork off that and make changes, *or* should we keep this PR in limbo and Meir can make his changes to a fork of my fork which I PR and add to this PR?

Finally, the things I want to fix I am putting on hold anyway because I am going to do the italics. Meir, feel free to work on the source.

### CODE REVIEW

**Comment by meirsadan** [comment]
Hey, thanks for adding me! I just skimmed through the glyphs file and would take a longer look over the weekend.
Also, I'd be happy to know how this interpolation was made? Is it an automatic interpolation/extrapolation process of condensing the typeface or has it been extracted from an existing source? I think I remember there already being a condensed Open Sans Hebrew?

**Comment by laerm0** [comment]
Hi Meir –

The Hebrew in here is the Open Sans Hebrew you're thinking of: I merged it in last fall. The three interpolated weights were done in Glyphs (using the Pablo distribution) from the two weights I had TTF source for.

**Comment by meirsadan** [comment]
Hey,

Sorry for taking this long to report back! I've reviewed the condensed style. 

I'm not sure how the condensed style is generated/interpolated? I know Yanek Iontef worked on the design but I'm not sure if the condensed was also done by him. I've done a mostly technical review here, as a design review will require more time...

Technical issues that need attention:

- The "geresh" and "gershayim" characters are missing from all the fonts – these characters aren't 100% necessary and sometimes interchangeable with "quote" and "dblquote", but this creates (vertical) alignment problems as well as unwanted directionality (Hebrew quote marks are always "typewriter" style).

- Diacritical marks (nikkud) are positioned too vertically close to the letters – the two exemplary "alef" glyphs (אַ אָ) look fine but usually these characters aren't used in modern applications, and most rasterisers use the positioning table to determine placement of diacritical marks.

- The dagesh in the pe looks fine to me, but the qof (ק), especially in the bold condensed version, has a very tight counter which barely contains the dagesh. The dagesh currently collides with the right vertical stem.

- In the "vav with holam" (וֹ), the holam point is centered above the vav. It's currently set slightly to the left. This should also be set in the positioning table.

- Some open-countered characters (kaf, resh, dalet) are spaced too tightly on their left sidebearings when compared to the overall spacing, and some open-countered letters (gimel) have too ample space on their left side. This issue isn't unique to the condensed style but these anomalies become very conspicuous in the narrow styles.

I should point out that the early access version of [Open Sans Hebrew Condensed](https://fonts.google.com/earlyaccess#Open+Sans+Hebrew+Condensed) has well set diacritic positions and the geresh and gershayim glyphs are present. Maybe you already are using it as such, but I think that version is a great point of reference.

I also used Pablo's excellent Font Testing Page which I made a [Hebrew section](http://oketz.com/testing/index-hebrew.php) for, to review the files.

Please ask if any more details are needed on any of the issues, or to take a look at any specific detail that you think needs attention. :>

**Comment by laerm0** [comment]
Hi @meirsadan –

Thank you again for the excellent feedback. I was working on other aspects of this project but today I have fixed the things you note. I still wonder about the qof with dagesh in the bold condensed: as you say, it is very close. Is it okay for the dagesh to come above of the left stem, or should it align to the top of that stem?* If yes, is it better to make a smaller dagesh or a wider counter?

Thanks again.

* like so:
screen region 2018-04-29 at 15 01 00

**Comment by davelab6** [comment]
@laerm0 what is needed to get this merged? :)

**Comment by laerm0** [comment]
Hints as good as the original, pretty much.

**Comment by davelab6** [comment]
I suggest to merge it now, then :)

**Comment by laerm0** [comment]
Hm. I see no conflicts on my side, so I dunno what the error is.

I pushed VTT hinted variable fonts to my fork today.

**Comment by davelab6** [comment]
In https://github.com/googlefonts/opensans/pull/3/commits I see only 4 commits. 

I think all your work is on `master` branch, so this can just be closed?

**Comment by laerm0** [comment]
Oh, that makes sense, yes I've been working on my master branch.

**Comment by davelab6** [comment]
Thanks again to @meirsadan for your insights!

**Pull request closed without merging**
